name: Go Test & Tidy Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Verify go.mod and go.sum
        run: go mod tidy && git diff --exit-code

      - name: Run Tests
        run: go test -v ./...
        
